### PR TITLE
Update warning banner

### PR DESCRIPTION
**Pull request by jonmcalder**

### CODE REVIEW

**Comment by datawookie** [comment]
Hey Jon,

Thanks for this. I think that it would be better to use the *permanent* address for the new site. Do you want to ask Steph if she can allocate joburg2019.satrdays.org for us? I can then use it to update the URL on netlify too.

Thanks,
Andrew.

**Comment by datawookie** [comment]
As for the 2017 site, let's do this with the final URL for the 2019 site.

**Comment by jonmcalder** [comment]
> I guess you don't want me to merge this yet... because the site will be automatically updated. I'll hang on until Steph has sorted out the URL and we've deployed the new site.

Nope - I removed the WIP from the title to indicate that this is ready to merge. Just wanted you to check it. Steph has deployed the sub-domain and the DNS update seems to have propagated already (at least for me it has).

**Comment by datawookie** [comment]
Sweet! Okay, let me ask Emma to push her updates.

**Pull request closed without merging**
